add container registry and validation

diff --git a/.github/workflows/build-container.yaml b/.github/workflows/build-container.yaml
--- a/.github/workflows/build-container.yaml
+++ b/.github/workflows/build-container.yaml
@@ -36,7 +36,7 @@ jobs:
         cancel-in-progress: false
 
       env:
-        IMAGE_NAME: ${{ inputs.registry }}/${{ github.event.repository.name }}/${{ inputs.name }}
+        IMAGE_NAME: ${{ env.CONTAINER_REGISTRY }}/${{ github.event.repository.name }}/${{ inputs.name }}
         IS_DEFAULT_BRANCH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
 
       outputs:
@@ -44,6 +44,22 @@ jobs:
         image: ${{ env.IMAGE_NAME }}
 
       steps:
+        - name: Validate environment
+          shell: bash
+          run: |
+            if [ -z "${{ secrets.GOOGLE_PROJECT_ID }}" ]; then
+              echo "Missing GOOGLE_PROJECT_ID secret"
+              exit 1
+            fi
+            if [ -z "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}" ]; then
+              echo "Missing WORKLOAD_IDENTITY_PROVIDER secret"
+              exit 1
+            fi
+            if [ -z "${{ secrets.ARTIFACT_SERVICE_ACCOUNT_EMAIL }}" ]; then
+              echo "Missing ARTIFACT_SERVICE_ACCOUNT_EMAIL secret"
+              exit 1
+            fi
+
         - name: Checkout 🛎️
           uses: actions/checkout@v4
 
